sql 1.


ALTER TABLE JOHN.ABITURIENTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE JOHN.ABITURIENTS CASCADE CONSTRAINTS;

CREATE TABLE JOHN.ABITURIENTS
(
  ID_ABITUR    ROWID,
  FIO          VARCHAR2(255 BYTE)               NOT NULL,
  ADRESS       VARCHAR2(255 BYTE)               NOT NULL,
  BIRTH_DATE   DATE                             NOT NULL,
  MEDAL_EXIST  CHAR(1 BYTE)                     NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX JOHN.ABITURIENTS_PK ON JOHN.ABITURIENTS
(ID_ABITUR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE JOHN.ABITURIENTS ADD (
  CONSTRAINT ABITURIENTS_PK
  PRIMARY KEY
  (ID_ABITUR)
  USING INDEX JOHN.ABITURIENTS_PK
  ENABLE VALIDATE);


DROP TABLE JOHN.EXAMS CASCADE CONSTRAINTS;

CREATE TABLE JOHN.EXAMS
(
  ROW_ID            ROWID                       NOT NULL,
  ID_ABITURIENT     ROWID                       NOT NULL,
  ID_PREDMET        ROWID                       NOT NULL,
  BALL              NUMBER                      NOT NULL,
  DATE_OF_COMPLETE  DATE                        NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE JOHN.EXAMS ADD (
  CONSTRAINT EXAMS__ABITUR_R01 
  FOREIGN KEY (ID_ABITURIENT) 
  REFERENCES JOHN.ABITURIENTS (ID_ABITUR)
  ENABLE VALIDATE,
  CONSTRAINT EXAMS__PR_R01 
  FOREIGN KEY (ID_PREDMET) 
  REFERENCES JOHN.PREDMETS (ID_PREDMET)
  ENABLE VALIDATE);


ALTER TABLE JOHN.PREDMETS
 DROP PRIMARY KEY CASCADE;

DROP TABLE JOHN.PREDMETS CASCADE CONSTRAINTS;

CREATE TABLE JOHN.PREDMETS
(
  ID_PREDMET  ROWID                             NOT NULL,
  PREDMET     VARCHAR2(255 CHAR)                NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX JOHN.PREDMETS_PK ON JOHN.PREDMETS
(ID_PREDMET)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE JOHN.PREDMETS ADD (
  CONSTRAINT PREDMETS_PK
  PRIMARY KEY
  (ID_PREDMET)
  USING INDEX JOHN.PREDMETS_PK
  ENABLE VALIDATE);



ALTER TABLE JOHN.SPECIALIUZATION
 DROP PRIMARY KEY CASCADE;

DROP TABLE JOHN.SPECIALIUZATION CASCADE CONSTRAINTS;

CREATE TABLE JOHN.SPECIALIUZATION
(
  ID_SPEC     ROWID                             NOT NULL,
  NAME        VARCHAR2(255 BYTE)                NOT NULL,
  FACULTY     VARCHAR2(255 BYTE)                NOT NULL,
  START_BALL  NUMBER                            NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX JOHN.SPECIALIUZATION_PK ON JOHN.SPECIALIUZATION
(ID_SPEC)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE JOHN.SPECIALIUZATION ADD (
  CONSTRAINT SPECIALIUZATION_PK
  PRIMARY KEY
  (ID_SPEC)
  USING INDEX JOHN.SPECIALIUZATION_PK
  ENABLE VALIDATE);




ALTER TABLE JOHN.SPEC_PRED
 DROP PRIMARY KEY CASCADE;

DROP TABLE JOHN.SPEC_PRED CASCADE CONSTRAINTS;

CREATE TABLE JOHN.SPEC_PRED
(
  ID_PRED       ROWID                           NOT NULL,
  ID_CODE_SPEC  ROWID                           NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX JOHN.SPEC_PRED_PK ON JOHN.SPEC_PRED
(ID_PRED, ID_CODE_SPEC)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE JOHN.SPEC_PRED ADD (
  CONSTRAINT SPEC_PRED_PK
  PRIMARY KEY
  (ID_PRED, ID_CODE_SPEC)
  USING INDEX JOHN.SPEC_PRED_PK
  ENABLE VALIDATE);

ALTER TABLE JOHN.SPEC_PRED ADD (
  CONSTRAINT SPEC_PRED_R01 
  FOREIGN KEY (ID_CODE_SPEC) 
  REFERENCES JOHN.SPECIALIUZATION (ID_SPEC)
  ENABLE VALIDATE,
  CONSTRAINT SPEC_PRED_R02 
  FOREIGN KEY (ID_PRED) 
  REFERENCES JOHN.PREDMETS (ID_PREDMET)
  ENABLE VALIDATE);
